version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=215384330
    #      - MYSQL_HOST=db
    #      - MYSQL_DATABASE=admin
    #      - MYSQL_USER=root
    #      - MYSQL_PASSWORD=mysql
    #      - MYSQL_ROOT_PASSWORD=mysql
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db

  db:
    image: postgres:latest
    #    image: mysql:latest
    volumes:
      - ./data/db:/var/lib/postgresql/data
    #      - ./data/db:/var/lib/mysql
    environment:
      #      - MYSQL_DATABASE=admin
      #      - MYSQL_USER=root
      #      - MYSQL_PASSWORD=mysql
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=215384330
    ports:
      - 5432:5432
      #     - 33066:3306
